In [12]:
# Types of programming languages
# Translator
# Compiled and Interpreted lanaguages
# How a Python program gets executed
# Variable and Constant

# Types of programming languages

- 1- Hilgh level language
- 2- Low level language

# High level language

- It is a human friendly computer language.
- The code is written in simple language like English.
- It is easy to read, learn and understand.
- **Examples-** C, C++, Python, Java, PHP, R etc.

# Low level language

- It is machine friendly.
- The code is writting using binary digits also known as bits (0,1)
- It is almost impossible to learn and understand for a human being.
- **Example-** Machine language is a low level language. It is also known as Binary language
- 0 and 1 are just signals

In [2]:
# 10010010100100
# 10010010010010
# 10010111100101
# 10010010011111

# Translator

- A translator is a software that converts the high level language code into machine code and vice versa.

# Types of translators

- 1- Compiler
- 2- Interpreter

# Compiler

- The compiler reads the whole high level language code first and then it converts the whole code into machine code at once.

# Interpreter

- It reads the high level language  code line by line and converts into machine code line by line.
- It reads and converts one line at a time.

# Compiled vs Interpreted languages

- The languages that use compiler as the translator are known as the compiled languages.
- C, C++, Java, VB etc.

- The languages that use interpreter as the translator are known as interpreted languages.
- Python, R, Ruby, PHP etc.

# Whether Python is interpreted or compiled?

# How a Python program gets executed

In [3]:
#include<stdio.h>
int aa`main()
{
    int a=10,b=20,c;
    c=a+b;
    print("%d",c);
    return 0;
    }

SyntaxError: invalid syntax (6794965.py, line 2)

In [1]:
print(10+20)

30


# Source Code

- The code that we write as a developer is known as source code.
- The extension of the Python source code is .py

# Intermediate Code

- As soon as we run the Python source code, compiler comes into picture.
- The compiler converts the source code  into intermediate code.
- The intermediate code in Python is known as Bytecode
- The extension of Python Bytecode file is .pyc
- If compiler catches any error in source code then Bytecode is not generated. In this case the whole program is not executed and we don't get any output.

# Machine Code

- As soon as compiler generates the Bytecode the interpreter comes into picture.
- The interpreter reads and converts the Bytecode into machine code line by line.
- As soon as interpreter catches any error then it stops execution.
- In this case the program is partially executed. Until the interpreter catches any error, it generates the output.

# Types of errors

- 1- Compile time error
- 2- Run time error

# Compile time errors

- The errors that are caught by the compiler at the time of compilation are known as compile time errors.

### Examples

- Syntax error
- Indentation error

# Run time errors

- The errors that are caught by the interpreter at the run time are known as run time errors.

### Examples

- 1- Name error
- 2- Type error
- 3- Value error
- 4- Index error
- 5- File not found error
- 6- Stop Iteration
- 7- Key error
- etc.

In [ ]:



Syntax error


In [ ]:



Name error



In [ ]:



Name error

Syntax error



In [7]:
print('Hello')
a=10
b=20
c=a+b
print(c

SyntaxError: unexpected EOF while parsing (1691340000.py, line 5)

In [1]:
print('Hello')
a=10
b=20
c=a+b
print(c)
print(d) # Name error
print('Hello Python')
print('Thanks')

Hello
30


NameError: name 'd' is not defined

In [9]:
print('Hello')
a=10
b=20
c=a+b
print(c)
print(d) # Name error
print('Hello Python')
print('Thanks'

SyntaxError: unexpected EOF while parsing (4092832761.py, line 8)

In [10]:
# Python has been developed in C language
# ABC language- Interpreted

In [11]:
# Compiled languages- better performance
# Interpreted languages- lower performnace- Easy syntax

# Variable and constant

# Variable (name)

- A variable is a container that contains some value.

# Constant (value)

- The value that a variable holds is a constant

In [13]:
a=10
# a- variable
# 10- constant (value)

In [11]:
age=25
# age- variable
# 25- value (constant)

In [2]:
0=34
print(0)

SyntaxError: cannot assign to literal (3839629154.py, line 1)

In [12]:
_0=34
print(_0)

34


In [6]:
_a_a=10
print(_a_a)

10


# Datatypes

- A datatype is a type identifier of the value that a variable holds.
- Different kind of values will have different behaviour so it is important to know the type of a value.

In [16]:
# type()- It gives the type of the value that a variable holds

In [15]:
# Basis datatypes
# Derived datatypes

# Basic Datatypes

# integer- int

In [17]:
# Any number whether it is +ive, -ive or 0 without a decimal point is an int value.

In [1]:
a=10000
print(a)
print(type(a))

10000
<class 'int'>


In [20]:
a=10
print(a,type(a))

10 <class 'int'>


In [21]:
a=-5
print(a,type(a))

-5 <class 'int'>


In [22]:
a=0
print(a,type(a))

0 <class 'int'>


# float

In [23]:
# - Any number whetehr +ive, -ive or 0 with a decimal point is a float value

In [15]:
a=2.5
print(a,type(a))

2.5 <class 'float'>


In [25]:
a=-3.6
print(a,type(a))

-3.6 <class 'float'>


In [26]:
a=0.0
print(a,type(a))

0.0 <class 'float'>


# complex

In [27]:
# - Any number in the form of a+bj is a complex value.
# - Where a is a real number and bj is an imaginary number.

In [3]:
a=5+7j
print(a,type(a))
print(id(a))

(5+7j) <class 'complex'>
2685609113360


In [1]:
a=2.5+3.2j
print(a,type(a))
print(abs(a))

(2.5+3.2j) <class 'complex'>
4.060788100849391


In [3]:
a=9+2j
print(a)
print(a.real)
print(a.imag)

(9+2j)
9.0
2.0


In [34]:
a=5j
print(a,type(a))

5j <class 'complex'>


In [35]:
a=5+2i
print(a)

SyntaxError: invalid syntax (4281827626.py, line 1)

In [3]:
a=-10+6j
print(a)
print(abs(a))

(-10+6j)
11.661903789690601


In [37]:
a=-5+2j
print(a,type(a))

(-5+2j) <class 'complex'>


# string- str

In [38]:
# Anything inside the ' ', " ",''' ''', """ """ is a string value

In [7]:
a='5'
print(a,type(a))

5 <class 'str'>


In [43]:
a='Python'
print(a,type(a))

Python <class 'str'>


In [41]:
a="Python"
print(a,type(a))

Python <class 'str'>


In [46]:
# Output- Python's Libraries

a="Python's Libraies"
print(a)

Python's Librraies


In [48]:
a='2.5'
print(a,type(a))

2.5 <class 'str'>


In [1]:
a='this is me'
print(a)

this is me


In [1]:
v="We are learning 'Data Scinece' from Learnbay"
print(v)

We are learning 'Data Scinece' from Learnbay


In [50]:
# Output- We are learning "Data Science" from Learnbay

a='We are learning "Data Scinece" from Learnbay'
print(a)

We are learning "Data Scinece" from Learnbay


In [53]:
a='''Hello world!
This is Python class'''

print(a)

Hello world!
This is Python class


In [54]:
a="""Hello world!
This is Python class"""
print(a)

Hello world!
This is Python class


In [55]:
# Hello world!
# This is "Python class"

In [57]:
a='''Hello world!
This is "Python class"'''
print(a)

Hello world!
This is "Python class"


In [58]:
# 'Hello world!
# This is Python class'

In [60]:
a="""'Hello world!
This is Python class'"""
print(a)

'Hello world!
This is Python class'


# Boolean- bool

In [61]:
# True and False are the boolean values

In [62]:
a=True
print(a,type(a))

True <class 'bool'>


In [63]:
a=False
print(a,type(a))

False <class 'bool'>


In [3]:
m="kanjjsf'jdwdgj'jsfsjfna"
print(m)

kanjjsf'jdwdgj'jsfsjfna


In [1]:
print("hello world")

hello world


In [5]:
a=None
print(a,type(a))

None <class 'NoneType'>


In [8]:
distance=395000
time=9000
speed=distance/time
print(speed)

43.888888888888886


In [2]:
a=2*2*2+2*2*3+2*3*2
print(a)

32


In [3]:
print("kannan")

kannan


In [4]:
print("kannan")
print("kannan")
print("kannan")

kannan
kannan
kannan


In [8]:
import numpy as np

In [10]:
len(np.random.randint(10,11,10000))

10000

In [4]:
'2'+chr(189)

'2½'

In [13]:
100 and 20

20

In [14]:
100 or 20

100

In [15]:
print(15 & 26)

10


In [26]:
print(15 | 26)
print(15 ^ 26)
print(~26)
print(3 << 4)
print(4 >> 2)

31
21
-27
48
1


In [1]:
print("kannadhsan")

kannadhsan


In [6]:
print("kannadhsan")
print("kannadhsan")
print("kannadhsan")

kannadhsan
kannadhsan
kannadhsan


In [5]:
if 6==6:
    print("yes")
     

yes


In [ ]:
 print()

In [2]:
import numpy as np
oo=np.random.randint(1,100,16).reshape(4,4)
print(oo)

[[96 41 97 94]
 [45 72 45  1]
 [42  8 59 97]
 [49 93 39 92]]


In [7]:
if 7==7:
    print("hello")

hello


In [9]:

print(10)

10


# None

In [3]:
# name="kanna"
# roll_number=None
# city="chenni"
# print(name,roll_number,city)

'name="kanna"\nroll_number=None\ncity="chenni"\nprint(name,roll_number,city)'

In [2]:
#print("airtel")

In [4]:
aa=True
print(aa)

True


In [10]:
ff=None
ii=bool(ff)
ii

False